# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('habil', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=10)),
                ('idaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Aula')),
                ('iddia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcicloescolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.CicloEscolar')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=10)),
                ('huelladigitalbase64', models.BinaryField()),
                ('idmaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Maestro')),
            ],
        ),
        migrations.AddField(
            model_name='hora',
            name='idhorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Horario'),
        ),
        migrations.AddField(
            model_name='hora',
            name='idmaestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Maestro'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='idhorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scasut.Horario'),
        ),
    ]
